Repository so2niko/Dp-193_proj1, pull requests merged in 2020-10, with the labels that each got.

#3 docs: add shop name
  README.md
Labels: documentation

#54 47 Fix eslint
  .eslintrc.js
Labels: bug

#53 Edit publisher
  app/helpers/publisher.js
  app/main.js
Labels: documentation

#52 I`v added regenerator-runtime
  package-lock.json
  package.json
  webpack.config.js
Labels: bug

#58 MVC Component Header
  app/components/header/header-controller.js
  app/components/header/header-model.js
  app/components/header/header-styles.scss
  app/components/header/header-view.js
  app/components/template/template-controller.js
  app/components/template/template-model.js
  app/components/template/template-view.js
  app/config/publisher-events.js
  app/helpers/publisher.js
  app/images/logo-1.png
  app/images/svg/search.svg
  app/main.js
  package-lock.json
  package.json
  webpack.config.js
Labels: enhancement

#57 MVC Component Filter
  .eslintrc.js
  app/components/filter/filter-controller.js
  app/components/filter/filter-model.js
  app/components/filter/filter-view.js
  app/components/filter/filter.scss
  app/css/_styles.scss
  app/css/main.scss
  app/helpers/publisher.js
  app/main.js
  index.html
Labels: enhancement

#66 Images in database are changed
  base/database.json
Labels: bug

#74 README.md is edited
  README.md
Labels: documentation

#75 Kundenko 71 Fix filter rendering
  app/components/filter/filter-controller.js
  app/components/filter/filter-view.js
Labels: bug

#77 Drozdov 55 slider
  app/components/cars-gallery/controller-cars-gallery.js
  app/components/header/header-view.js
  app/components/slider/slider-controller.js
  app/components/slider/slider-model.js
  app/components/slider/slider-view.js
  app/components/slider/slider.scss
  app/main.js
Labels: enhancement

#84 Header changed v3
  app/components/header/header-view.js
  app/main.js
Labels: bug

#88 Fix Slider Component, Footer, Header
  app/components/cars-gallery/cars-gallery.scss
  app/components/filter/filter.scss
  app/components/slider/slider.scss
  app/css/main.scss
  app/main.js
  index.html
Labels: bug

#97 Added closing filter on layout click
  app/components/filter/filter-view.js
  app/components/filter/filter.scss
Labels: enhancement

#91 Helper 69
  app/components/car-details/controller-car-details.js
  app/components/car-details/model-car-details.js
  app/components/car-details/style-car-details.scss
  app/components/car-details/view-car-details.js
  app/config/publisher-events.js
  app/main.js
  package-lock.json
Labels: enhancement

#99 Fix: car details window closing
  app/components/car-details/controller-car-details.js
  app/components/car-details/model-car-details.js
  app/components/car-details/view-car-details.js
  app/components/filter/filter-view.js
Labels: bug
